"""add username

Revision ID: 680b3748447a
Revises: 2dcdc2c34156
Create Date: 2021-03-09 11:51:27.260541

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '680b3748447a'
down_revision = '2dcdc2c34156'
branch_labels = None
depends_on = None


metadata = sa.MetaData()
users_table = sa.Table(
    'users',
    metadata,
    sa.Column('id', sa.Integer),
    sa.Column('username', sa.String, nullable=False, index=True),
    sa.Column('password', sa.String, nullable=False),
    sa.Column('email', sa.String, nullable=False),
    sa.Column('registered_at', sa.DateTime, default=sa.func.current_timestamp(
    ), nullable=False),
    sa.Column('is_admin', sa.Boolean, nullable=False, default=False,
              comment='If user has admin priviliges in app'),
    sa.Column('is_deleted', sa.Boolean, nullable=False, default=False),

    sa.PrimaryKeyConstraint('id', name='pk__users'),
    sa.UniqueConstraint('email', name='uq__users__email'),
    sa.UniqueConstraint('username', name='uq__users__username'),
)


def upgrade():
    # add new nullable column
    op.add_column('users', sa.Column('username', sa.String(), nullable=True))
    op.create_index(op.f('ix__users__username'),
                    'users', ['username'], unique=True)

    # migrate data
    query = users_table.update().values(
        username=sa.func.split_part(users_table.c.email, '@', 1)
    )
    op.execute(query)

    # make new column non-nullable
    op.alter_column('users', 'username', nullable=False)


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix__users__username'), table_name='users')
    op.drop_column('users', 'username')
    # ### end Alembic commands ###
