"""add index on blacklisted_tokens table

Revision ID: c276d90383a9
Revises: 92fff7ae5003
Create Date: 2021-02-23 13:08:57.080303

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c276d90383a9'
down_revision = '92fff7ae5003'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq__blacklist_tokens__token', 'blacklist_tokens', type_='unique')
    op.create_index(op.f('ix__blacklist_tokens__token'), 'blacklist_tokens', ['token'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix__blacklist_tokens__token'), table_name='blacklist_tokens')
    op.create_unique_constraint('uq__blacklist_tokens__token', 'blacklist_tokens', ['token'])
    # ### end Alembic commands ###
