"""add index and unique constraint on created_by and title combination

Revision ID: ef6d484b3d39
Revises: 680b3748447a
Create Date: 2021-04-13 10:15:08.821013

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ef6d484b3d39'
down_revision = '680b3748447a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq__projects__title', 'projects', type_='unique')
    op.create_index('ix__projects__created_by__title', 'projects', ['created_by', 'title'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix__projects__created_by__title', table_name='projects')
    op.create_unique_constraint('uq__projects__title', 'projects', ['title'])
    # ### end Alembic commands ###
